### ISSUE TITLE
Tardis cannot land in a closed area

### ISSUE THREAD

**Issue by AniieGirlHub** [Jeryn99/TardisRefined#105]
### Issue description

Simply I want to land it inside my base, and it just lands in the same coords, but at the top of it.

### Steps to reproduce

1. Have a functional tardis
2. Put the coords in a 3 block tall place
3. Land it
4. It will be at the roof

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

Forge 43.2.6

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

I have installed alongside Xaero's minimap and world map, so I can put waypoints and not miss the coords.

**Comment by CommandrMoose** [comment]
There isn't enough information to work with here. Can you please demonstrate where you're attempting to land, what co-ordinates you're targeting and where you're actually landing.

**Comment by CommandrMoose** [comment]
It's been a year. Going to mark this as closed.
