### ISSUE TITLE
Server crash when landing + odds and sods

### ISSUE THREAD

**Issue by Rasttny** [Jeryn99/TardisRefined#109]
### Issue description

What happened: Server crashed a few times when a player was landing the tardis.

Expected: The tardis to land and the server not crash.

A couple of things have happened to cause timeouts and crashes which will be reflected in the 4 logs I have attached via gist.

### Steps to reproduce

1.) Play on a server with multiple people
2.) a player takes off
3.) a player hits the throttle to land
4.) server freezes then crashes

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Forge

### Mod Loader version

forge-1.19.2-43.2.0

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

No other mods.

Server running Java 17.0.6 Eclipse Adoptium fork.

### Attach the relevant crash report file or log file: (Don't know how to find a crash report file? See the [Minecraft Wiki Tutorial](https://minecraft.fandom.com/wiki/Tutorials/How_to_get_a_crash_report)

https://gist.github.com/Rasttny/dfde88b1b925eaf4ef29692e0f8d3bb7

**Comment by CommandrMoose** [comment]
This issue appears to be a problem with the Watchdog system on your server terminating after not responding for a certain amount of time.  This will most likely be halting due to the scanning logic attempting to find a suitable location to land.

This should be rectified in the next release.

**Comment by Suff99** [comment]
Can you re-produce this with V1?

**Comment by CommandrMoose** [comment]
We haven't heard from this issue in over a year. Please let us know if this is still occurring for you. We are aware of this issue and have somewhat of a fix that should resolve this.
