### ISSUE TITLE
XYZ Coordinate Hotbar messages not displaying

### ISSUE THREAD

**Issue by zorex73** [Jeryn99/TardisRefined#162]
### Issue description

the subtitle to show increment and x y z don't show up when I alter them, also how do you lower the x, y, or z numbers I've been messing with them and I can't figure it out. thanks.

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

fabric 0.14.21

### Tardis Refined version

v1.0

**Comment by Suff99** [comment]
You increment and decrement the coordinate values by punching and right clicking

**Comment by zorex73** [comment]
That's not what I'm confused about, when I punch or right click the subtitles that are supposed show up don't. The ones that say the increment size like 1x, 10x, 100x, 1000x.

**Comment by 50ap5ud5** [comment]
Can you reproduce this issue if you only install Tardis Refined?

**Comment by CommandrMoose** [comment]
We haven't heard from you in a while. Please let us know if this issue still persists for you and open this ticket back up :)
