### ISSUE TITLE
[BUG] 10 second server delay while interior generates

### ISSUE THREAD

**Issue by thejudge156** [Jeryn99/TardisRefined#41]
**Describe the bug**
The interior of the TARDIS takes about 10 seconds to generate per TARDIS.

**To Reproduce**
1. Spawn a TARDIS
2. Attempt entering
3. Wait

**Expected behavior**
Close to no delay.

**Platform:**
 - Game version: 1.19.2
 - Platform: Fabric

**Comment by 50ap5ud5** [comment]
Thank you for reporting this. We are aware of the issue, it is being looked into. :)

**Comment by Jeryn99** [comment]
I consider this fixed in 1.20.2 due to @CommandrMoose
