### ISSUE TITLE
Root Door hitbox may be wrong depending on facing

### ISSUE THREAD

**Issue by thejudge156** [Jeryn99/TardisRefined#64]
### Issue description

(Thanks Pheonix for telling me)
Not really a gameplay issue, but the Root Door, when facing anywhere but North or South, will have its hitbox in the wrong place.

### Steps to reproduce

1. Place 2 root doors, one facing north and one facing south
2. Place 2 more root doors, one facing east and one facing west
3. Observe

### Minecraft version

1.19.2 (Latest)

### Mod Loader Platform type

Fabric

### Mod Loader version

Fabric Loader 0.14.10

### Tardis Refined version

Pre-release v0.1

### Other relevant versions

Based on the codebase, this should apply to both mod loaders.

**Comment by CommandrMoose** [comment]
Good catch, we'll look into this.

**Comment by CommandrMoose** [comment]
Resolved in latest changes. To be released soon.
